services:
  - type: web
    name: facturation-app&#10;    envVars:&#10;      - key: APP_DEBUG&#10;        value: "true"&#10;      - key: APP_ENV&#10;        value: production
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://facturation-app-prcw.onrender.com
      - key: APP_KEY
        value: base64:YXBwbGljYXRpb25rZXlnZW5lcmF0ZWRhdXRvbWF0aWNhbGx5
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d6okdr75r7bs73e7g4k0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: facturation_db_2eu2
      - key: DB_USERNAME
        value: facturation_db_2eu2_user
      - key: DB_PASSWORD
        value: nQ7kfF7nWEBJqd3vlDm5XDL2Sz5N4flc
